version: '3'
services:
  navegatec-frontend:
    build: 
      context: .
    volumes:
      - type: bind
        source: ./
        target: /app
      - /app/node_modules
    ports:
      - "5175:5175"
      - "5176:5176"
      - "4444:4444"